#!/bin/sh

patch_all() {
  patch_dirs=$(ls patch/)
  current_dir=$(pwd)
  for i in $patch_dirs; do
    echo "- Patch working at dir $i..."
    cd "$i"

    patches=$(find "$current_dir/patch/$i" -name \*.patch | tr "\n" " ")
    for j in $patches; do
      echo "- Patching file $j..."
      # Reset Before patch
      git reset --hard HEAD
      patch -t -p1 -N -l -i "$j"
    done

    cd "$current_dir"
  done
}

patch_all