#!/bin/sh

patch_all() {
  patch_dirs=$(ls patch/)
  current_dir=$(pwd)
  for i in $patch_dirs; do
    echo "- Patch working at dir $i..."
    cd "$i"

    patches=$(find "$current_dir/patch/$i" -name \*.patch | tr "\n" " ")
    for j in $patches; do
      echo "- Patching file $j..."
      # Reset Before patch
      git reset --hard HEAD
      patch -t -p1 -N -l -i "$j"
    done

    cd "$current_dir"
  done
  # add for extract.erofs
  if [ "$(uname -o)" = "Cygwin" ]; then
    if [ -d "extract" ]; then
      echo "- Detect cygwin environment, patch extract.erofs source"
      list_of_extract=$(find extract/extract -name \*.cpp | tr "\n" " ")
      for i in $list_of_extract; do
        # Remove unsupport attribute on clang-8
        sed -i "s/\[\[unlikely\]\]//g" "$i"
        sed -i "s/\[\[likely\]\]//g" "$i"
      done
    fi
  fi
}

patch_all